name: astronomy
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.6.0
  intl: ^0.18.1
  go_router: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/default.png
  fonts:
    - family: Work Sans
      fonts:
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 500
