// Mocks generated by Mockito 5.4.2 from annotations
// in astronomy/test/app/infra/repositories/apod_today/apod_today_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:astronomy/app/infra/datasources/apod_today/apod_today_datasource.dart'
    as _i3;
import 'package:astronomy/app/infra/models/apod_model.dart' as _i2;
import 'package:astronomy/core/interfaces/network_info.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApodModel_0 extends _i1.SmartFake implements _i2.ApodModel {
  _FakeApodModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApodTodayDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockApodTodayDatasource extends _i1.Mock
    implements _i3.ApodTodayDatasource {
  @override
  _i4.Future<_i2.ApodModel> fetchApodToday() => (super.noSuchMethod(
        Invocation.method(
          #fetchApodToday,
          [],
        ),
        returnValue: _i4.Future<_i2.ApodModel>.value(_FakeApodModel_0(
          this,
          Invocation.method(
            #fetchApodToday,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ApodModel>.value(_FakeApodModel_0(
          this,
          Invocation.method(
            #fetchApodToday,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ApodModel>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
